-- Supabase Schema for Aviator Landing Page
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql

-- 1. Claims Table
CREATE TABLE IF NOT EXISTS public.claims (
  id TEXT PRIMARY KEY,
  name TEXT,
  phone TEXT,
  email TEXT,
  promo_code TEXT DEFAULT 'AVIATOR500',
  bonus_percentage NUMERIC DEFAULT 500,
  amount NUMERIC DEFAULT 50000,
  currency TEXT DEFAULT 'INR',
  session_token TEXT,
  status TEXT DEFAULT 'APPROVED',
  timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 2. Sessions Table (Flight history)
CREATE TABLE IF NOT EXISTS public.sessions (
  id TEXT PRIMARY KEY,
  session_token TEXT,
  attempt_number INT,
  duration NUMERIC,
  multiplier NUMERIC,
  outcome TEXT,
  bet_amount NUMERIC,
  currency TEXT DEFAULT 'INR',
  timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 3. Live Winners Feed Table
CREATE TABLE IF NOT EXISTS public.winners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  avatar TEXT DEFAULT 'star',
  multiplier NUMERIC NOT NULL,
  amount NUMERIC NOT NULL,
  currency TEXT DEFAULT 'INR',
  time TEXT DEFAULT 'Just now',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 4. Platform Stats Table
CREATE TABLE IF NOT EXISTS public.stats (
  id INT PRIMARY KEY DEFAULT 1,
  total_flights BIGINT DEFAULT 142857,
  total_bonus_claimed BIGINT DEFAULT 41304886,
  active_players INT DEFAULT 194,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Seed initial stats row if not present
INSERT INTO public.stats (id, total_flights, total_bonus_claimed, active_players)
VALUES (1, 142857, 41304886, 194)
ON CONFLICT (id) DO NOTHING;

-- Seed initial winners if table is empty
INSERT INTO public.winners (name, avatar, multiplier, amount, currency, time)
SELECT 'StarChaser', 'star', 1.57, 315, 'INR', 'Just now'
WHERE NOT EXISTS (SELECT 1 FROM public.winners);

INSERT INTO public.winners (name, avatar, multiplier, amount, currency, time)
SELECT 'Player ••••7', 'mask', 1.72, 3440, 'INR', 'Just now'
WHERE (SELECT count(*) FROM public.winners) < 2;

INSERT INTO public.winners (name, avatar, multiplier, amount, currency, time)
SELECT 'RaniOfRisk', 'crown', 1.25, 250, 'INR', '1m ago'
WHERE (SELECT count(*) FROM public.winners) < 3;

INSERT INTO public.winners (name, avatar, multiplier, amount, currency, time)
SELECT 'JetMaster99', 'rocket', 14.80, 29600, 'INR', '2m ago'
WHERE (SELECT count(*) FROM public.winners) < 4;

-- Enable Row Level Security (RLS)
ALTER TABLE public.claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.winners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stats ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read/write access (for public landing page endpoints)
CREATE POLICY "Allow public read on claims" ON public.claims FOR SELECT USING (true);
CREATE POLICY "Allow public insert on claims" ON public.claims FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on sessions" ON public.sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert on sessions" ON public.sessions FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on winners" ON public.winners FOR SELECT USING (true);
CREATE POLICY "Allow public insert on winners" ON public.winners FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on stats" ON public.stats FOR SELECT USING (true);
CREATE POLICY "Allow public update on stats" ON public.stats FOR ALL USING (true);
